import pandas as pd


def create_temporal_lag_features(df: pd.DataFrame, lags: int = 2) -> pd.DataFrame:
    """Engineers temporal lag features for multivariate telemetry data.

    Expects columns: ['cabinet_temp', 'cpu_load', 'health_score']
    """
    df = df.copy()

    for lag in range(1, lags + 1):
        if "cabinet_temp" in df.columns:
            df[f"Temp_Lag_{lag}"] = df["cabinet_temp"].shift(lag)
        if "cpu_load" in df.columns:
            df[f"CPU_Lag_{lag}"] = df["cpu_load"].shift(lag)
        if "health_score" in df.columns:
            df[f"Health_Lag_{lag}"] = df["health_score"].shift(lag)

    # Drop initial rows containing NaN values generated by shifting
    return df.dropna().reset_index(drop=True)
